ALTER TYPE audit_action_enum ADD VALUE IF NOT EXISTS 'CREATE_ROLE';
ALTER TYPE audit_action_enum ADD VALUE IF NOT EXISTS 'UPDATE_ROLE';
ALTER TYPE audit_action_enum ADD VALUE IF NOT EXISTS 'DELETE_ROLE';
