export enum EmailType {
  INVITE = "INVITE",
  REMINDER = "REMINDER",
  SPRINT_FEEDBACK = "SPRINT_FEEDBACK",
}

export enum EmailStatus {
  SENT = "SENT",
  FAILED = "FAILED",
}

export enum TokenType {
  MAGIC_LINK = "MAGIC_LINK",
}

export enum AuditAction {
  CREATE_PROJECT = "CREATE_PROJECT",
  UPDATE_PROJECT = "UPDATE_PROJECT",
  ADD_PROJECT_MEMBERS = "ADD_PROJECT_MEMBERS",
  UPDATE_PROJECT_MEMBER = "UPDATE_PROJECT_MEMBER",
  REMOVE_PROJECT_MEMBER = "REMOVE_PROJECT_MEMBER",
  CREATE_SPRINT = "CREATE_SPRINT",
  UPDATE_SPRINT = "UPDATE_SPRINT",
  ASSIGN_PROJECT_MEMBERS_TO_SPRINT = "ASSIGN_PROJECT_MEMBERS_TO_SPRINT",
  GENERATE_PEER_RATINGS = "GENERATE_PEER_RATINGS",
  CREATE_QUESTION = "CREATE_QUESTION",
  UPDATE_QUESTION = "UPDATE_QUESTION",
  DELETE_QUESTION = "DELETE_QUESTION",
  TOGGLE_QUESTION_STATUS = "TOGGLE_QUESTION_STATUS",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  GENERATE_SECURITY_PIN = "GENERATE_SECURITY_PIN",
  SEND_SPRINT_FEEDBACK_EMAIL = "SEND_SPRINT_FEEDBACK_EMAIL",
  VERIFY_SECURITY_PIN = "VERIFY_SECURITY_PIN",
  REQUEST_RATING = "REQUEST_RATING",
  SUBMIT_RATING = "SUBMIT_RATING",
  UPDATE_SPRINT_RATING_REQUESTS = "UPDATE_SPRINT_RATING_REQUESTS",
}
